# Alacritty configuration file format
# https://alacritty.org/config-alacritty.html

# General configurations
live_config_reload = true

[shell]
program = "zsh"

# Environment variables to set when running the command.
[env]
TERM = "xterm-256color"

# Window configurations
[window]
decorations = "Transparent"
dimensions = { columns = 145, lines = 45 }
padding = { x = 12, y = 12 }
# opacity = 0.90
# blur = true

# Font configurations
[font]
size = 13.0
normal = { family = "MonaspiceNe Nerd Font Mono", style = "Regular" }
bold = { family = "MonaspiceNe Nerd Font Mono", style = "Bold" }
italic = { family = "MonaspiceNe Nerd Font Mono", style = "Italic" }
bold_italic = { family = "MonaspiceNe Nerd Font Mono", style = "Bold Italic" }
