# Alacritty configuration file format
# https://alacritty.org/config-alacritty.html

# General configurations
live_config_reload = true

[shell]
program = "zsh"

# Environment variables to set when running the command.
[env]
TERM = "xterm-256color"

# Window configurations
[window]
decorations = "Transparent"
dimensions = { columns = 140, lines = 48 }
padding = { x = 12, y = 12 }
opacity = 0.90
blur = true 
