# Starship Configuration

# Prompt format
format = "$all"

# Show the time prompt to the right
right_format = "$time"

# Timeout for starship to scan files (in milliseconds).
scan_timeout = 500

# Timeout for commands executed by starship (in milliseconds).
command_timeout = 1000

# Inserts a blank line between shell prompts
add_newline = true

# Replace the ❯ symbol in the prompt with ➜
[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

# Packages

[time]
disabled = false 

[directory]
truncation_length = 8
truncation_symbol = "…/"

[swift]
disabled = false 

[ruby]
disabled = true

[battery]
disabled = true
