# Enable True Color (24-bit) support
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"

# Allow passthrough of escape sequences to the outer terminal
set -gq allow-passthrough on

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on
