# Enable True Color (24-bit) support
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"

# Allow passthrough of escape sequences to the outer terminal
set -gq allow-passthrough on

set -g prefix C-b           # 前缀键使用 Ctrl-b

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded" # 重新加载配置并显示提示

unbind %                     # 取消默认的左右分割按键
unbind '"'                   # 取消默认的上下分割按键
bind | split-window -h       # 使用 | 左右分割面板
bind - split-window -v       # 使用 - 上下分割面板

bind -r h resize-pane -L 5   # 使用 h 向左调整面板大小
bind -r j resize-pane -D 5   # 使用 j 向下调整面板大小
bind -r k resize-pane -U 5   # 使用 k 向上调整面板大小
bind -r l resize-pane -R 5   # 使用 l 向右调整面板大小
bind -r m resize-pane -Z     # 使用 m 最大化或还原面板

set -g base-index 1          # 窗口编号从 1 开始
set -g renumber-windows on   # 关闭窗口后自动重新编号，保持窗口编号连续
setw -g pane-base-index 1    # 面板编号从 1 开始

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

## - catppuccin theme
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavour 'mocha' # latte, frappe, macchiato, mocha

### Make the status line more pleasant.
set -g status-right '%Y-%m-%d %H:%M '

set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_text " #{window_name}"
set -g @catppuccin_window_current_text " #{window_name}#{?window_zoomed_flag,(),}"
set -g @catppuccin_status_modules_right "directory" # date_time"
set -g @catppuccin_status_modules_left "session"
set -g @catppuccin_status_right_separator_inverse "no"
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_directory_text "#{b:pane_current_path}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
