# Enable True Color (24-bit) support
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"

# Allow passthrough of escape sequences to the outer terminal
set -gq allow-passthrough on

set -g prefix C-b           # 前缀键使用 Ctrl-b

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded" # 重新加载配置并显示提示

unbind %                     # 取消默认的左右分割按键
unbind '"'                   # 取消默认的上下分割按键
bind | split-window -h       # 使用 | 左右分割面板
bind - split-window -v       # 使用 - 上下分割面板

set -g base-index 1          # 窗口编号从 1 开始
set -g renumber-windows on   # 关闭窗口后自动重新编号，保持窗口编号连续
setw -g pane-base-index 1    # 面板编号从 1 开始
