## =====================
## Install Core formulae
## =====================
brew "bat"          # cat clone with syntax highlighting and Git integration
brew "coreutils"    # GNU core utilities, commands prefixed with "g" (gls, gcp, ...)
brew "delta"        # syntax highlighting pager for git and diff output
brew "eza"          # ls clone with more features
brew "fd"           # find clone with more features
brew "fzf"          # fuzzy finder
brew "git"
brew "jq"           # JSON processor
brew "ripgrep"      # faster grep clone
brew "zoxide"       # zoxide is a smarter cd command, inspired by z and autojump

## =====================
## Terminal utilities
## =====================
cask "ghostty"
cask "iterm2"
cask "termius"

brew "asc"          # App Store Connect CLI tool https://asccli.sh/
brew "awscli"       # AWS Command Line Interface
brew "btop"         # Resource monitor
brew "fileicon"     # macOS CLI for managing custom icons for files and folders
brew "gh"           # GitHub CLI tool
brew "lazygit"
brew "mas"          # Mac App Store command-line interface
brew "mole"         # Clean, uninstall, optimize, and monitor your Mac from the terminal
brew "pandoc"       # Universal document converter
brew "sqlite"       # Command-line interface for SQLite databases
brew "tmux"
brew "watchexec"    # Executes commands in response to file modifications

## =====================
## Fonts
## =====================
cask "font-aporetic"
cask "font-hack"
cask "font-jetbrains-mono-nerd-font"
cask "font-maple-mono-nf-cn"
cask "font-source-code-pro"
cask "font-symbols-only-nerd-font"
cask "sf-symbols"

## =====================
## Input method
## =====================
cask "input-source-pro"
tap "laishulu/homebrew", trusted: true
brew "macism"

## =====================
## Neovim
## =====================
brew "neovim"

## =====================
## Development environment
## =====================
brew "bun"
brew "chezscheme"
brew "cmake"
brew "fvm"
brew "lua"
brew "luajit"
brew "luarocks"
brew "node"
brew "python"
brew "ruby"
brew "rust"
brew "shellcheck"
brew "shfmt"
brew "stylua"
brew "swift-format"
brew "swiftlint"
brew "tree-sitter"
brew "tree-sitter-cli"
brew "xcode-build-server"
brew "zig"
brew "zls"

cask "android-studio"
cask "flutter"
cask "fork"
cask "visual-studio-code"

## =====================
## Applications
## =====================
tap "alielsokary/tap", trusted: { cask: "caskhub" }
cask "caskhub"
cask "google-chrome"
cask "localsend"
cask "mac-mouse-fix"
cask "movist-pro"
cask "numi"
cask "obsidian"
cask "raycast"
cask "rectangle-pro"
cask "tableplus"
cask "telegram"

## =====================
## App Store
## =====================
mas "The Unarchiver", id: 425424353
mas "QQ", id: 451108668
mas "Xcode", id: 497799835
mas "Developer", id: 640199958
mas "微信", id: 836500024
mas "Marked 2", id: 890031187
mas "TestFlight", id: 899247664
mas "Things", id: 904280696
mas "Shadowrocket", id: 932747118
mas "企业微信", id: 1189898970
mas "ColorSlurp", id: 1287239339
mas "MindNode Classic", id: 1289197285
mas "Core Data Lab", id: 1460684638
mas "腾讯会议", id: 1484048379
mas "RocketSim", id: 1504940162
mas "抖音", id: 1640407382
