#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                on
yabai -m config window_border_width          3
yabai -m config active_window_border_color   0xff3b99fc
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  12
yabai -m config bottom_padding               12
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   06

# yabai -m config --space 1 layout float

yabai -m space 1 --label app
yabai -m space 2 --label dev
yabai -m space 3 --label mail
yabai -m space 4 --label misc
yabai -m space 5 --label V
yabai -m space 6 --label VI
yabai -m space 7 --label VII
yabai -m space 8 --label VIII
yabai -m space 9 --label IX
yabai -m space 10 --label X

yabai -m rule --add app="^Alacritty$" border=on

yabai -m rule --add app="^(Music|音乐)$" space=4

yabai -m rule --add app="^Numi$" manage=off
yabai -m rule --add app="^Surge$" manage=off
yabai -m rule --add app="^Things$" manage=on
yabai -m rule --add app="^Movist Pro$" manage=off
yabai -m rule --add app="^CleanMyMac X$" border=off manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^(Calendar|日历)$" manage=off
yabai -m rule --add app="^(System Preferences|系统偏好设置)$" manage=off

yabai -m rule --add app="^QQ$" manage=off
yabai -m rule --add app="^Slack$" manage=off
yabai -m rule --add app="^Twitter$" manage=off
yabai -m rule --add app="^Telegram$" manage=off
yabai -m rule --add app="^(WeChat|微信)$" border=off manage=off
yabai -m rule --add app="^(WeCom|企业微信)$" border=off manage=off

yabai -m rule --add app="^Simulator$" border=off manage=off
yabai -m rule --add app="^JetBrains Toolbox$" manage=off

yabai -m rule --add app="^(Android Studio|AppCode|DataGrip)$" title="^Rename$" manage=off
yabai -m rule --add app="^(Android Studio|AppCode|DataGrip)$" title="^Preferences$" manage=off
yabai -m rule --add app="^(Android Studio|AppCode|DataGrip)$" title="^Tip of the Day$" manage=off

yabai -m rule --add app="^Android Studio$" title="^Welcome to Android Studio$" manage=off
yabai -m rule --add app="^AppCode$" title="^Welcome to AppCode$" manage=off
yabai -m rule --add app="^DataGrip$" title="^Welcome to DataGrip$" manage=off

# yabai -m config external_bar all:27:0

echo "yabai configuration loaded.."
